# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 696f195303f43678e6baca816fd1d5811a62e8def12a1c0e4413a0acb240a772183ad147c57a79eb4a2e0674b8f47b6806ef32d8544dfaf1d33220c348262a00

test:
  secret_key_base: 59521b8a3cfb991b38634f5b139bbc890d15ba4da25bc64b70a172cbbe69d1e41660a423dba0b254094489823df5d6db32d8dc7c1a442232f60e3654a07d1734

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
